---
version: '2.4'
networks:
  net_db_bridge_green: {driver: bridge}
  net_db_bridge_red: {driver: bridge}
  net_rabbit_bridge_green: {driver: bridge}
  net_rabbit_bridge_red: {driver: bridge}
  net_ne_bridge_red: {driver: bridge}
  net_ne_bridge_green: {driver: bridge}
  net_db_bridge_amb_green: {driver: bridge}
  net_db_bridge_amb_red: {driver: bridge}
  net_rabbit_bridge_amb_green: {driver: bridge}
  net_rabbit_bridge_amb_red: {driver: bridge}
  net_ne_bridge_amb_red: {driver: bridge}
  net_ne_bridge_amb_green: {driver: bridge}
services:
  bridge_affirmation:
    cpus: 0.1
    entrypoint: yarn watcher:affirmation-request
    env_file: ./.env
    environment: [NODE_ENV=production,
                  ORACLE_BRIDGE_MODE=ERC_TO_NATIVE,
                  'COMMON_HOME_BRIDGE_ADDRESS=${TB_HOME_BRIDGE_ADDRESS}',
                  'COMMON_FOREIGN_BRIDGE_ADDRESS=${TB_FOREIGN_BRIDGE_ADDRESS}',
                  'ORACLE_QUEUE_URL=${TB_QUEUE_URL}',
                  'ORACLE_REDIS_URL=${TB_REDIS_URL}',
                  'ORACLE_FOREIGN_START_BLOCK=${TB_FOREIGN_START_BLOCK}',
                  'ORACLE_VALIDATOR_ADDRESS=${TB_ORACLE_VALIDATOR_ADDRESS}']
    image: poanetwork/tokenbridge-oracle:latest
    mem_limit: 500m
    networks: [net_db_bridge_green, 
               net_rabbit_bridge_green,
               net_ne_bridge_green]
    restart: unless-stopped
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    depends_on:
      - redis
      - rabbit  
  bridge_shutdown:
    cpus: 0.1
    mem_limit: 500m
    image: poanetwork/tokenbridge-oracle:latest
    env_file: ./.env
    environment: [NODE_ENV=production,
                  ORACLE_BRIDGE_MODE=ERC_TO_NATIVE,
                  'ORACLE_REDIS_URL=${TB_REDIS_URL}',
                  'ORACLE_SHUTDOWN_SERVICE_POLLING_INTERVAL=${TB_SHUTDOWN_SERVICE_POLLING_INTERVAL}',
                  'ORACLE_SIDE_RPC_URL=${TB_SIDE_RPC_URL}',
                  'ORACLE_SHUTDOWN_CONTRACT_ADDRESS=${TB_SHUTDOWN_CONTRACT_ADDRESS}',
                  'ORACLE_SHUTDOWN_CONTRACT_METHOD=${TB_SHUTDOWN_CONTRACT_METHOD}']
    restart: unless-stopped
    entrypoint: yarn manager:shutdown
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    networks: [net_db_bridge_green]
    depends_on:
      - redis
  bridge_request:
    cpus: 0.1
    entrypoint: yarn watcher:signature-request
    env_file: ./.env
    environment: [NODE_ENV=production,
                  ORACLE_BRIDGE_MODE=ERC_TO_NATIVE,
                  'COMMON_HOME_BRIDGE_ADDRESS=${TB_HOME_BRIDGE_ADDRESS}',
                  'COMMON_FOREIGN_BRIDGE_ADDRESS=${TB_FOREIGN_BRIDGE_ADDRESS}',
                  'ORACLE_QUEUE_URL=${TB_QUEUE_URL}',
                  'ORACLE_REDIS_URL=${TB_REDIS_URL}',
                  'ORACLE_HOME_START_BLOCK=${TB_HOME_START_BLOCK}', 
                  'ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY=${TB_ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY}']
    image: poanetwork/tokenbridge-oracle:latest
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    mem_limit: 500m
    networks: [net_db_bridge_red, 
               net_rabbit_bridge_red,
               net_ne_bridge_red]
    restart: unless-stopped
    depends_on:
      - redis
      - rabbit  
  bridge_senderhome:
    cpus: 0.1
    entrypoint: yarn sender:home
    env_file: ./.env
    environment: [NODE_ENV=production,
                  ORACLE_BRIDGE_MODE=ERC_TO_NATIVE,
                  'COMMON_HOME_BRIDGE_ADDRESS=${TB_HOME_BRIDGE_ADDRESS}',
                  'COMMON_FOREIGN_BRIDGE_ADDRESS=${TB_FOREIGN_BRIDGE_ADDRESS}',
                  'ORACLE_QUEUE_URL=${TB_QUEUE_URL}',
                  'ORACLE_REDIS_URL=${TB_REDIS_URL}',
                  'ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY=${TB_ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY}']
    image: poanetwork/tokenbridge-oracle:latest
    mem_limit: 500m
    networks: [net_db_bridge_red,
               net_rabbit_bridge_red,
               net_ne_bridge_red]
    restart: unless-stopped
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}    
    depends_on:
      - redis
      - rabbit  
  bridge_transfer:
    cpus: 0.1
    entrypoint: yarn watcher:transfer
    env_file: ./.env
    environment: [NODE_ENV=production,
                  ORACLE_BRIDGE_MODE=ERC_TO_NATIVE,
                  'COMMON_HOME_BRIDGE_ADDRESS=${TB_HOME_BRIDGE_ADDRESS}',
                  'COMMON_FOREIGN_BRIDGE_ADDRESS=${TB_FOREIGN_BRIDGE_ADDRESS}',
                  'ORACLE_QUEUE_URL=${TB_QUEUE_URL}',
                  'ORACLE_REDIS_URL=${TB_REDIS_URL}',
                  'ORACLE_FOREIGN_START_BLOCK=${TB_FOREIGN_START_BLOCK}',
                  'ORACLE_VALIDATOR_ADDRESS=${TB_ORACLE_VALIDATOR_ADDRESS}']
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    image: poanetwork/tokenbridge-oracle:latest
    mem_limit: 500m
    networks: [net_db_bridge_green, 
               net_rabbit_bridge_green,
               net_ne_bridge_green]
    restart: unless-stopped
    depends_on:
      - redis
      - rabbit  
  rabbit:
    cpus: 0.3
    environment: [RABBITMQ_NODENAME=node@rabbit]
    hostname: rabbit
    image: rabbitmq:3
    mem_limit: 500m
    networks: [net_rabbit_bridge_red,
               net_rabbit_bridge_green]
    restart: unless-stopped
    volumes: ['~/bridge_data/rabbitmq:/var/lib/rabbitmq/mnesia']
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
  redis:
    command: [redis-server, --appendonly, 'yes']
    cpus: 0.1
    hostname: redis
    image: redis:4
    mem_limit: 500m
    networks: [net_db_bridge_red,
               net_db_bridge_green]
    restart: unless-stopped
    volumes: ['~/bridge_data/redis:/data']
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}

  ne:
    container_name: ne
    image: nethermind/nethermind:latest
    networks: [net_ne_bridge_green,
               net_ne_bridge_red,
               net_ne_bridge_amb_green,
               net_ne_bridge_amb_red]
    command:
      --config xdai
      --baseDbPath /nethermind
      --JsonRpc.Enabled true
      --JsonRpc.Host 0.0.0.0
      --Init.StoreReceipts false
      --TxPool.Size 8192
      --Pruning.Mode Hybrid
      --Pruning.CacheMb 1024
      --Sync.FastSync true
      --Sync.FastBlocks true
      --Sync.DownloadBodiesInFastSync false
      --Sync.DownloadReceiptsInFastSync false
      --Sync.DownloadHeadersInFastSync false
    volumes:
      - ~/ne-data/logs:/nethermind/logs
      - ~/ne-data/nethermind_db:/nethermind/nethermind_db
    expose:
      - "8545"
    ports:
      - "30304:30303/tcp"
      - "30304:30303/udp"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  bridge_amb_affirmation:
    cpus: 0.1
    entrypoint: yarn watcher:affirmation-request
    env_file: ./.env
    environment: [NODE_ENV=production,
                  ORACLE_BRIDGE_MODE=ARBITRARY_MESSAGE,
                  'COMMON_HOME_BRIDGE_ADDRESS=${AMB_HOME_BRIDGE_ADDRESS}',
                  'COMMON_FOREIGN_BRIDGE_ADDRESS=${AMB_FOREIGN_BRIDGE_ADDRESS}',
                  'ORACLE_QUEUE_URL=${AMB_QUEUE_URL}',
                  'ORACLE_REDIS_URL=${AMB_REDIS_URL}',
                  'ORACLE_FOREIGN_START_BLOCK=${AMB_FOREIGN_START_BLOCK}',
                  'ORACLE_VALIDATOR_ADDRESS=${AMB_ORACLE_VALIDATOR_ADDRESS}']
    image: poanetwork/tokenbridge-oracle:latest
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    mem_limit: 500m
    networks: [net_db_bridge_amb_green, 
               net_rabbit_bridge_amb_green,
               net_ne_bridge_amb_green]
    restart: unless-stopped
    depends_on:
      - redis-amb
      - rabbit-amb
  bridge_amb_information:
    cpus: 0.1
    entrypoint: yarn watcher:information-request
    env_file: ./.env
    environment: [NODE_ENV=production, 
                  ORACLE_BRIDGE_MODE=ARBITRARY_MESSAGE,
                  'COMMON_HOME_BRIDGE_ADDRESS=${AMB_HOME_BRIDGE_ADDRESS}',
                  'COMMON_FOREIGN_BRIDGE_ADDRESS=${AMB_FOREIGN_BRIDGE_ADDRESS}',
                  'ORACLE_QUEUE_URL=${AMB_QUEUE_URL}',
                  'ORACLE_REDIS_URL=${AMB_REDIS_URL}',
                  'ORACLE_HOME_START_BLOCK=${AMB_HOME_START_BLOCK}',
                  'ORACLE_VALIDATOR_ADDRESS=${AMB_ORACLE_VALIDATOR_ADDRESS}']
    image: poanetwork/tokenbridge-oracle:latest
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    mem_limit: 500m
    networks: [net_db_bridge_amb_green,
               net_rabbit_bridge_amb_green,
               net_ne_bridge_amb_green]
    restart: unless-stopped
    depends_on:
      - redis-amb
      - rabbit-amb
  bridge_amb_request:
    cpus: 0.1
    entrypoint: yarn watcher:signature-request
    env_file: ./.env
    environment: [NODE_ENV=production, 
                  ORACLE_BRIDGE_MODE=ARBITRARY_MESSAGE,
                  'COMMON_HOME_BRIDGE_ADDRESS=${AMB_HOME_BRIDGE_ADDRESS}',
                  'COMMON_FOREIGN_BRIDGE_ADDRESS=${AMB_FOREIGN_BRIDGE_ADDRESS}',
                  'ORACLE_QUEUE_URL=${AMB_QUEUE_URL}',
                  'ORACLE_REDIS_URL=${AMB_REDIS_URL}', 
                  'ORACLE_HOME_START_BLOCK=${AMB_HOME_START_BLOCK}',
                  'ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY=${AMB_ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY}']
    image: poanetwork/tokenbridge-oracle:latest
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    mem_limit: 500m
    networks: [net_db_bridge_amb_red, 
               net_rabbit_bridge_amb_red,
               net_ne_bridge_amb_red]
    restart: unless-stopped
    depends_on:
      - redis-amb
      - rabbit-amb
  bridge_amb_shutdown:
    cpus: 0.1
    entrypoint: yarn manager:shutdown
    env_file: ./.env
    environment: [NODE_ENV=production,
                  ORACLE_BRIDGE_MODE=ARBITRARY_MESSAGE,
                  'ORACLE_REDIS_URL=${AMB_REDIS_URL}',
                  'ORACLE_SHUTDOWN_SERVICE_POLLING_INTERVAL=${AMB_SHUTDOWN_SERVICE_POLLING_INTERVAL}',
                  'ORACLE_SIDE_RPC_URL=${AMB_SIDE_RPC_URL}',
                  'ORACLE_SHUTDOWN_CONTRACT_ADDRESS=${AMB_SHUTDOWN_CONTRACT_ADDRESS}',
                  'ORACLE_SHUTDOWN_CONTRACT_METHOD=${AMB_SHUTDOWN_CONTRACT_METHOD}']
    image: poanetwork/tokenbridge-oracle:latest
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    mem_limit: 500m
    networks: [net_db_bridge_amb_green]
    restart: unless-stopped
    depends_on:
      - redis-amb
  bridge_amb_senderhome:
    cpus: 0.1
    entrypoint: yarn sender:home
    env_file: ./.env
    environment: [NODE_ENV=production,
                  ORACLE_BRIDGE_MODE=ARBITRARY_MESSAGE,
                  'COMMON_HOME_BRIDGE_ADDRESS=${AMB_HOME_BRIDGE_ADDRESS}',
                  'COMMON_FOREIGN_BRIDGE_ADDRESS=${AMB_FOREIGN_BRIDGE_ADDRESS}',
                  'ORACLE_QUEUE_URL=${AMB_QUEUE_URL}',
                  'ORACLE_REDIS_URL=${AMB_REDIS_URL}',
                  'ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY=${AMB_ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY}']
    image: poanetwork/tokenbridge-oracle:latest
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    mem_limit: 500m
    networks: [net_db_bridge_amb_red, 
               net_rabbit_bridge_amb_red,
               net_ne_bridge_amb_red]
    restart: unless-stopped
    depends_on:
      - redis-amb
      - rabbit-amb
  rabbit-amb:
    cpus: 0.3
    environment: [RABBITMQ_NODENAME=node@rabbit-amb]
    hostname: rabbit-amb
    image: rabbitmq:3
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    mem_limit: 500m
    networks: [net_rabbit_bridge_amb_red,
               net_rabbit_bridge_amb_green]
    restart: unless-stopped
    volumes: ['~/amb_bridge_data/rabbitmq:/var/lib/rabbitmq/mnesia']
  redis-amb:
    command: [redis-server, --appendonly, 'yes']
    cpus: 0.1
    hostname: redis-amb
    image: redis:4
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    mem_limit: 500m
    networks: [net_db_bridge_amb_red, 
               net_db_bridge_amb_green]
    restart: unless-stopped
    volumes: ['~/amb_bridge_data/redis:/data']